### ISSUE TITLE
Cleanup some dxf files so they more suited for laser cutting

### ISSUE THREAD

**Issue by edkolev** [bishboria/ErgoDox#1]
Hi, and thanks for providing these files - I used them to laser cut a case.

However, the laser-cutting-company complained that the files had some minor issues, like:
- the lines were not connected everywhere
- some line were duplicated (2 line on top of each other)
- the lines were not combined into a polyline

That's why I had to cleanup some of the files, which leads me to my question: are you interested in merging back these changes? You can see my changes here https://github.com/edkolev/ErgoDox

I haven't updated all the files because the company did that themselves, but didn't send me back the modified files.

**Comment by tekamolo** [comment]
What is the program you are opening the dxf files with? I tried with Autocad 2007 and there is an error:

Invalid or incomplete DXF input -- drawing discarded.

I don't know if this is a compatible version problem or it is a corruption file problem.

**Comment by bishboria** [comment]
Apologies for only just noticing this issue!

I grabbed the dxf files from another source and didn't check to see if they were valid… If you open a PR with the files updated I'd gladly merge the changes in.

**Comment by edkolev** [comment]
@tekamolo, I edited the files with LibreCAD, then I sent them to a friend to check them with AutoCAD. He applied some minor changes and sent them back. I'll ask him which version of AutoCAD  he edited them with.

BTW I have no problems editing the files with LibreCAD. Maybe you're having issues due to the old AutoCAD version.

@bishboria, I'll open a PR

**Comment by edkolev** [comment]
The files have been edited in autocad 2011, but have been saved for 2004
